FROM node:20.10.0

WORKDIR /app

COPY package*.json ./

RUN npm install --verbose

COPY . .

# ENV NODE_ENV="production"

RUN npm run build

RUN npm run build:server

EXPOSE 4000

# CMD ["node", ".server/server.js"]

CMD ["npm", "run", "start"]

