version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
    ports:
      - 4000:4000
