FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]

# docker rm $(docker ps -aq)
# docker rmi $(docker images -a -q)
# docker build -f Dockerfile.prod .
# docker images
# docker container run -d -p 4000:4000 04829f408cf9